# Coding Quiz #1

## 1부터 100 사이의 홀수와 짝수의 누적합을 구하시오. (10점)

In [15]:
even_sum = 0
odd_sum = 0

for i in range(1, 101):
  # 코드 입력
  if i % 2 == 0:  # 2로 나눠서 나머지 0이면 짝수
      even_sum += i 
  elif i % 2 != 0: # 2로 나눠서 나머지 0이 아니면 홀수
      odd_sum += i

print("짝수의 누적합:", even_sum)
print("홀수의 누적합:", odd_sum)

짝수의 누적합: 2550
홀수의 누적합: 2500

## 2부터 100 사이의 소수를 구하는 코드를 작성하시오. (30점)

In [16]:
def judgement(N):
    # 입력 N은 2이상의 자연수로만 한정한다.
    for i in range(2, N):  # 1과 자기자신 N을 제외하고 나누어진다면 소수가 아니다.
        if N % i == 0:
            return False
    else:
        return True # 그 이외에는 소수이다.


prime_numbers = []
for i in range(2, 101):
    # 코드 입력
    if judgement(i) == True:  # 소수 판정 결과 True이면
        prime_numbers.append(i)  # 그 수를 prime_numbers 리스트에 넣는다.

print(prime_numbers)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]

## 가장 짧은 도시 이름을 출력하는 코드를 작성하시오. (30점)

In [19]:
cities = ['daejeon', 'seoul', 'daegu', 'busan', 'chuncheon', 'uijeongbu']

# 코드 입력
len_cities = []
for city in cities:
    len_cities.append(len(city))  # len_cities 리스트에 도시이름 수를 저장.

for city in cities:
    if len(city) == min(len_cities):  # 도시이름의 글자수 리스트의 최소값(5)과 일치하는 도시이름만 출력한다.
        print(city, end=' ')
    
#print(len_cities)

seoul daegu busan

## 나이에 따른 입장료를 계산하는 코드를 작성하시오. (30점)

* 1~7세: 1000원
* 8~20세: 2000원
* 21~40세: 3000원
* 41~세: 1500원

In [20]:
age = 30
pay = 0

# 코드 입력
def cal(age):  # 나이에 따라 입장료 계산하는 함수
    if 1 <= age <= 7:
        return 1000
    elif 8 <= age <= 20:
        return 2000
    elif 21 <= age <= 40:
        return 3000
    elif age >= 41:
        return 1500

pay = cal(age)
print("나이: {0}, 입장료: {1}".format(age, pay))

나이: 30, 입장료: 3000